### PR TITLE
rdflib 6.1.1, add noarch python, tests, maintainer

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Notes:
- alternative to (and includes)  #21
- overhaul metadata
- make noarch python
- add unit test suite
- adds self as maintainer :wave:

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Review by satra — COMMENTED** [review]
overall LGTM. do you know why the tests only include linux now. i.e. what happened to the windows and osx tests.

**Comment by bollwyvl** [comment]
It can be `noarch: python` now, which means just one build. Generally, on conda-forge, whenever we _can_ do simpler builds, we _should_, as then we don't have to build for `{python x platform x etc}`. `noarch` packages are also better for reproducibility, as this version will continue to work, even on future pythons and platufroms, without "archaeolgical" builds, which nobody enjoys.

And to clarify: It wasn't actually even _running_ tests, before, just building and importing... it could have been added there, of course, but upstream already does a [pretty wide matrix](https://github.com/RDFLib/rdflib/blob/master/.github/workflows/validate.yaml#L20). Re-running the test suite under coverage, here, is really just for verifying that we don't miss key dependency changes. It can still happen, of course! But much less likely, and I have found it to be worth if for the occasional fiddling with test dependencies, skips (usually due to docker network issues), and thresholds.

**Comment by nicholascar** [comment]
Hi all, I'm not really familiar with conda builds but I gather, from the above, that the improvements we've made with pytests and so on in rdflib have resulted in better testing downstream (here). I hope so!

If there are any packaging suggestions you have for rdflib, please do let me know and we'll take them up. Thanks again.

**Comment by bollwyvl** [comment]
Hey thanks for following up!

> Hi all, I'm not really familiar with conda builds but I gather, from the
> above, that the improvements we've made with pytests and so on in rdflib
> have resulted in better testing downstream (here). I hope so!
>
Yes, the test suite is looking fine, and predictable. We added a few test
skips, but 70ish percent from the sdist is quite respectable for such a
large API surface, run out of repo.

Chasing higher coverage is a mug's game, of course, but I guess hypothesis
can always chip away at edge cases, especially for things like round
tripping parsers.

> If there are any packaging suggestions you have for rdflib, please do let
> me know and we'll take them up. Thanks again.
>
Everything is looking fine: the tools are modern, without being bleeding
edge.

>

**Pull request merged**
